dotfiles_dir = "dotfiles"

[settings.dots]

# Stuff that goes in ~/.config
btop = { direct = true, source = "btop", target = ".config/btop" }
fish = { direct = true, source = "fish", target = ".config/fish" }

# Stuff that goes in ~/
editorconfig = { direct = true, source = "editorconfig", target = ".editorconfig" }
inputrc = { direct = true, source = "inputrc", target = ".inputrc" }
