# To overwrite existing symlinks:
#   bombadil link && bombadil unlink && bombadil link

dotfiles_dir = "dotfiles"

[settings.dots]

# Stuff that goes in ~/.config
btop = { direct = true, source = "btop", target = ".config/btop" }
fish = { direct = true, source = "fish", target = ".config/fish" }
kitty = { direct = true, source = "kitty", target = ".config/kitty" }
nvim = { direct = true, source = "nvim", target = ".config/nvim" }

# Stuff that goes in ~/
editorconfig = { direct = true, source = "editorconfig", target = ".editorconfig" }
inputrc = { direct = true, source = "inputrc", target = ".inputrc" }

# Git
gitconfig = { direct = true, source = "git/config", target = ".gitconfig" }
gitignore = { direct = true, source = "git/ignore", target = ".gitignore.global" }
